server:
  port: 8080
spring:
  activemq:
    broker-url: tcp://192.168.162.131:61616
    user: admin
    password: admin
  kafka:
    template:
      default-topic:
queue: springboot-queue
topic: spring-topic